# correspondence between the h36m official name of action/camera and our preprocessed id.
# by Xiaoxuan Ma

H36M_CAM_INFO = {
    '54138969': 'ca_01',
    '55011271': 'ca_02',
    '58860488': 'ca_03',
    '60457274': 'ca_04',
}

H36M_ACT_INFO = {
    'Directions-1': 'act_02_subact_01',
    'Directions-2': 'act_02_subact_02',
    'Discussion-1': 'act_03_subact_01',
    'Discussion-2': 'act_03_subact_02',
    'Eating-1': 'act_04_subact_01',
    'Eating-2': 'act_04_subact_02',
    'Greeting-1': 'act_05_subact_01',
    'Greeting-2': 'act_05_subact_02',
    'Phoning-1': 'act_06_subact_01',
    'Phoning-2': 'act_06_subact_02',
    'Posing-1': 'act_07_subact_01',
    'Posing-2': 'act_07_subact_02',
    'Purchases-1': 'act_08_subact_01',
    'Purchases-2': 'act_08_subact_02',
    'Sitting-1': 'act_09_subact_01',
    'Sitting-2': 'act_09_subact_02',
    'SittingDown-1': 'act_10_subact_01',
    'SittingDown-2': 'act_10_subact_02',
    'Smoking-1': 'act_11_subact_01',
    'Smoking-2': 'act_11_subact_02',
    'TakingPhoto-1': 'act_12_subact_01',
    'TakingPhoto-2': 'act_12_subact_02',
    'Waiting-1': 'act_13_subact_01',
    'Waiting-2': 'act_13_subact_02',
    'Walking-1': 'act_14_subact_01',
    'Walking-2': 'act_14_subact_02',
    'WalkingDog-1': 'act_15_subact_01',
    'WalkingDog-2': 'act_15_subact_02',
    'WalkingTogether-1': 'act_16_subact_01',
    'WalkingTogether-2': 'act_16_subact_02',
}

H36M_ACT_INFO_CONVERT = {
    'S11': {
        'Directions-2': 'Directions',
        'Discussion-2': 'Discussion 2',
        'Eating-2': 'Eating',
        'Greeting-1': 'Greeting 2',
        'Greeting-2': 'Greeting',
        'Phoning-1': 'Phoning 3',
        'Phoning-2': 'Phoning 2',
        'Posing-2': 'Posing',
        'Purchases-2': 'Purchases',
        'Sitting-2': 'Sitting',
        'SittingDown-1': 'SittingDown',
        'SittingDown-2': 'SittingDown 1',
        'Smoking-1': 'Smoking 2',
        'Smoking-2': 'Smoking',
        'TakingPhoto-1': 'Photo 1',
        'TakingPhoto-2': 'Photo',
        'Waiting-2': 'Waiting',
        'Walking-2': 'Walking',
        'WalkingDog-1': 'WalkDog 1',
        'WalkingDog-2': 'WalkDog',
        'WalkingTogether-1': 'WalkTogether 1',
        'WalkingTogether-2': 'WalkTogether'
    },
    'S9': {
        'Directions-2': 'Directions',
        'Discussion-2': 'Discussion 2',
        'Eating-2': 'Eating',
        'Greeting-2': 'Greeting',
        'Phoning-1': 'Phoning 1',
        'Phoning-2': 'Phoning',
        'Posing-2': 'Posing',
        'Purchases-2': 'Purchases',
        'Sitting-2': 'Sitting',
        'SittingDown-1': 'SittingDown',
        'SittingDown-2': 'SittingDown 1',
        'Smoking-2': 'Smoking',
        'TakingPhoto-1': 'Photo 1',
        'TakingPhoto-2': 'Photo',
        'Waiting-2': 'Waiting',
        'Walking-2': 'Walking',
        'WalkingDog-1': 'WalkDog 1',
        'WalkingDog-2': 'WalkDog',
        'WalkingTogether-1': 'WalkTogether 1',
        'WalkingTogether-2': 'WalkTogether'
    },
    'S8': {
        'Directions-2': 'Directions',
        'Discussion-2': 'Discussion',
        'Eating-2': 'Eating',
        'Greeting-2': 'Greeting',
        'Phoning-1': 'Phoning 1',
        'Phoning-2': 'Phoning',
        'Posing-2': 'Posing',
        'Purchases-2': 'Purchases',
        'Sitting-2': 'Sitting',
        'SittingDown-1': 'SittingDown',
        'SittingDown-2': 'SittingDown 1',
        'Smoking-2': 'Smoking',
        'TakingPhoto-1': 'Photo 1',
        'TakingPhoto-2': 'Photo',
        'Waiting-2': 'Waiting',
        'Walking-2': 'Walking',
        'WalkingDog-1': 'WalkDog 1',
        'WalkingDog-2': 'WalkDog',
        'WalkingTogether-1': 'WalkTogether 1',
        'WalkingTogether-2': 'WalkTogether 2'
    },
    'S7': {
        'Directions-2': 'Directions',
        'Discussion-2': 'Discussion',
        'Eating-2': 'Eating',
        'Greeting-2': 'Greeting',
        'Phoning-1': 'Phoning 2',
        'Phoning-2': 'Phoning',
        'Posing-2': 'Posing',
        'Purchases-2': 'Purchases',
        'Sitting-2': 'Sitting',
        'SittingDown-1': 'SittingDown',
        'SittingDown-2': 'SittingDown 1',
        'Smoking-2': 'Smoking',
        'TakingPhoto-1': 'Photo',
        'TakingPhoto-2': 'Photo 1',
        'WalkingDog-1': 'WalkDog 1',
        'WalkingDog-2': 'WalkDog',
        'WalkingTogether-1': 'WalkTogether 1',
        'WalkingTogether-2': 'WalkTogether'
    },
    'S6': {
        'Directions-2': 'Directions',
        'Discussion-1': 'Discussion 1',
        'Discussion-2': 'Discussion',
        'Eating-2': 'Eating 2',
        'Eating-1': 'Eating 1',
        'Greeting-2': 'Greeting',
        'Phoning-2': 'Phoning',
        'Posing-1': 'Posing 2',
        'Posing-2': 'Posing',
        'Purchases-2': 'Purchases',
        'SittingDown-1': 'SittingDown 1',
        'SittingDown-2': 'SittingDown',
        'Smoking-2': 'Smoking',
        'TakingPhoto-1': 'Photo',
        'TakingPhoto-2': 'Photo 1',
        'Waiting-1': 'Waiting 3',
        'Waiting-2': 'Waiting',
        'Walking-2': 'Walking',
        'WalkingDog-1': 'WalkDog 1',
        'WalkingDog-2': 'WalkDog',
        'WalkingTogether-1': 'WalkTogether 1',
        'WalkingTogether-2': 'WalkTogether'
    },
    'S1': {
        'Discussion-2': 'Discussion',
        'Directions-2': 'Directions',
        'Eating-2': 'Eating',
        'Eating-1': 'Eating 2',
        'Greeting-2': 'Greeting',
        'Phoning-2': 'Phoning',
        'Posing-2': 'Posing',
        'Purchases-2': 'Purchases',
        'SittingDown-1': 'SittingDown 2',
        'SittingDown-2': 'SittingDown',
        'Smoking-2': 'Smoking',
        'TakingPhoto-1': 'Photo 1',
        'TakingPhoto-2': 'TakingPhoto',
        'Waiting-2': 'Waiting',
        'Walking-2': 'Walking',
        'WalkingDog-1': 'WalkingDog 1',
        'WalkingDog-2': 'WalkingDog',
        'WalkingTogether-1': 'WalkTogether 1',
        'WalkingTogether-2': 'WalkTogether'
    },
    'S5': {
        'Discussion-1': 'Discussion 2',
        'Discussion-2': 'Discussion 3',
        'Eating-2': 'Eating',
        'Eating-1': 'Eating 1',
        'Phoning-2': 'Phoning',
        'Posing-2': 'Posing',
        'Purchases-2': 'Purchases',
        'Sitting-2': 'Sitting',
        'SittingDown-1': 'SittingDown',
        'SittingDown-2': 'SittingDown 1',
        'Smoking-2': 'Smoking',
        'TakingPhoto-1': 'Photo',
        'TakingPhoto-2': 'Photo 2',
        'Waiting-2': 'Waiting 2',
        'Walking-2': 'Walking',
        'WalkingDog-1': 'WalkDog 1',
        'WalkingDog-2': 'WalkDog',
        'WalkingTogether-1': 'WalkTogether 1',
        'WalkingTogether-2': 'WalkTogether'
    },
}